# Generated by Django 2.1.4 on 2019-01-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Aboutme',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_details', models.CharField(max_length=200)),
                ('contact_link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('year', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('githublink', models.CharField(max_length=200)),
                ('technologyused', models.TextField()),
                ('instructor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
